server {
    listen 5233;

    location / {
        proxy_pass http://radicale:5232;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_http_version 1.1;
    }
}
